#if !canImport(ObjectiveC)
import XCTest

extension BundlesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BundlesTests = [
        ("testDataResource", testDataResource),
        ("testDecodableResource", testDecodableResource),
        ("testJSONResource", testJSONResource),
        ("testStringResource", testStringResource),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BundlesTests.__allTests__BundlesTests),
    ]
}
#endif
